[general]
import = [
    "theme.toml",
]

[font]
size = 15.0
normal = { family = "Iosevka Term", style = "Regular" }

[window]
#decorations = "none"
padding = { x = 15, y = 5 }
option_as_alt = "Both"
#opacity = 0.95

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
    { key = "[", mods = "Control", mode = "Vi", action = "ToggleViMode" },
]
