[general]
import = [
    "theme.toml",
]

[font]
size = 15.0
normal = { family = "Berkeley Mono Variable" }

[window]
#decorations = "none"
padding = { x = 10, y = 5 }
option_as_alt = "Both"
#opacity = 0.95

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "[", mods = "Control", mode = "Vi", action = "ToggleViMode" },
]
